"""
spice_engine.py

SPICE Netlist Generator and 500-Run Monte Carlo Component Tolerance Yield Analyzer.
Directly models amplifier.kicad_pcb frontend (LMP7721 femtoamp TIA, LTC6268 buffer, R1=1M, C1=2pF)
with statistical variance and sensitivity tornado ranking.
"""

import math
import random
from typing import Dict, List, Any, Optional, Tuple


class SPICEEngine:
    """
    Simulates:
    1. SPICE netlist synthesis for the amplifier.kicad_pcb frontend.
    2. Monte Carlo component tolerance sweeps (100 to 1000 trials).
    3. Transfer function H(s), bandwidth distribution, gain peaking, and noise margins.
    4. Manufacturing yield analysis against design limits (70 to 90 kHz bandwidth).
    5. Sensitivity Tornado ranking identifying dominant variance drivers (C1 vs R1 vs parasitics).
    """

    DEFAULT_R1 = 1.0e6      # 1 MOhm feedback resistor
    DEFAULT_C1 = 2.0e-12    # 2 pF feedback capacitor
    DEFAULT_CPAR = 1.2e-12  # 1.2 pF PCB trace & fixture parasitic capacitance
    LMP7721_GBW = 17.0e6    # 17 MHz Gain-Bandwidth Product
    SPEC_MIN_FC_KHZ = 70.0  # -3dB cutoff minimum limit
    SPEC_MAX_FC_KHZ = 90.0  # -3dB cutoff maximum limit
    SPEC_MAX_PEAKING_DB = 1.5 # Maximum acceptable gain peaking

    def __init__(self):
        pass

    def generate_spice_netlist(
        self,
        r1_ohms: float = DEFAULT_R1,
        c1_farads: float = DEFAULT_C1,
        c_par_farads: float = DEFAULT_CPAR,
        input_current_na: float = 2.5
    ) -> str:
        """
        Generates production SPICE netlist (.cir / .sp) representation of the amplifier circuit.
        """
        netlist = f"""* =====================================================================
* Corkscrew-Filter Bio-Instrumentation Frontend SPICE Subcircuit
* Board: amplifier.kicad_pcb | Target: LMP7721 Femtoamp TIA + LTC6268 Buffer
* Generated by Atlas Fields Studio Autonomous EDA Engine
* =====================================================================

.title Nanopore Femtoamp Transimpedance Amplifier Simulation
.option nomod post probe

* --- Power Supplies ---
VCC VDD 0 DC 3.3
VEE VSS 0 DC -3.3
VBIAS V_PORE_BIAS 0 DC 0.100

* --- Input Nanopore Flowcell Signal Model ---
* Open-pore baseline current + translocation pulse injection
I_PORE 0 N_IN_TIA EXP (0.0 {input_current_na}n 1u 50n 50u 200n)
C_PAR_WELL N_IN_TIA 0 {c_par_farads * 1e12:.2f}p

* --- Front-End TIA Stage (U2: TI LMP7721) ---
* Inverting configuration with ultra-low input bias current (3 fA)
X_U2 0 N_IN_TIA VDD VSS N_TIA_OUT LMP7721_MACROMODEL
R1 N_IN_TIA N_TIA_OUT {r1_ohms / 1e6:.3f}MEG TC1=0.0001
C1 N_IN_TIA N_TIA_OUT {c1_farads * 1e12:.2f}p

* --- High-Speed Analog Buffer Stage (U16: ADI LTC6268) ---
* 4 GHz GBW low-distortion unity gain buffer driving 50 Ohm output
C_HPF N_TIA_OUT N_BUF_IN 100n
R_BIAS N_BUF_IN 0 100k
X_U16 N_BUF_IN N_BUF_OUT VDD VSS N_BUF_OUT LTC6268_BUFFER_MODEL
R_TERM N_BUF_OUT N_SMA_OUT 49.9

* --- Simulation Directives ---
.ac dec 20 100 10Meg
.tran 10n 100u
.noise V(N_SMA_OUT) I_PORE dec 10 100 1Meg

* --- Macromodel Placeholders ---
.subckt LMP7721_MACROMODEL IN_P IN_N VCC VEE OUT
E_GAIN OUT 0 IN_P IN_N 1.0e6
R_IN IN_P IN_N 1.0e14
C_IN IN_P IN_N 2.5p
R_OUT OUT 0 50
.ends

.subckt LTC6268_BUFFER_MODEL IN_P IN_N VCC VEE OUT
E_BUF OUT 0 IN_P IN_N 1.0
R_IN IN_P IN_N 1.0e12
C_IN IN_P 0 0.45p
R_OUT OUT 0 10
.ends

.end
"""
        return netlist

    def run_monte_carlo(
        self,
        num_runs: int = 500,
        r1_tolerance_pct: float = 1.0,
        c1_tolerance_pct: float = 5.0,
        parasitic_tolerance_pct: float = 10.0,
        gbw_tolerance_pct: float = 8.0,
        num_bins: int = 20
    ) -> Dict[str, Any]:
        """
        Executes a multi-trial Monte Carlo tolerance sweep on passive feedback network and parasitics.
        Evaluates yield against bandwidth limits (70 to 90 kHz) and peaking limits.
        """
        n_trials = max(50, min(2000, int(num_runs)))
        r_tol = max(0.05, float(r1_tolerance_pct)) / 100.0
        c_tol = max(0.1, float(c1_tolerance_pct)) / 100.0
        par_tol = max(0.5, float(parasitic_tolerance_pct)) / 100.0
        gbw_tol = max(0.5, float(gbw_tolerance_pct)) / 100.0

        r0 = self.DEFAULT_R1
        c0 = self.DEFAULT_C1
        cpar0 = self.DEFAULT_CPAR
        gbw0 = self.LMP7721_GBW

        fc_samples_khz = []
        peaking_samples_db = []
        in_spec_flags = []

        r_samples = []
        c_samples = []
        cpar_samples = []

        for _ in range(n_trials):
            # Sample parameters from Gaussian distribution (3 sigma = tolerance)
            r_val = r0 * (1.0 + random.gauss(0.0, r_tol / 3.0))
            c_val = c0 * (1.0 + random.gauss(0.0, c_tol / 3.0))
            cpar_val = cpar0 * (1.0 + random.gauss(0.0, par_tol / 3.0))
            gbw_val = gbw0 * (1.0 + random.gauss(0.0, gbw_tol / 3.0))

            r_samples.append(r_val)
            c_samples.append(c_val)
            cpar_samples.append(cpar_val)

            # Second-order closed-loop TIA transfer function bandwidth
            # fc = 1 / (2 * pi * R * C) with secondary pole correction from op-amp GBW
            w_ideal = 1.0 / (r_val * c_val)
            f_ideal_hz = w_ideal / (2.0 * math.pi)

            # Damping factor zeta = 0.5 * sqrt(GBW / (2*pi * R * (C + Cpar)))
            ctot = c_val + cpar_val
            w_opamp = 2.0 * math.pi * gbw_val
            zeta = 0.5 * math.sqrt(w_opamp / max(1.0, (1.0 / (r_val * ctot))))

            # Secondary pole correction
            f_actual_hz = f_ideal_hz * (1.0 - 0.04 * (cpar_val / c_val))
            fc_khz = f_actual_hz / 1000.0
            fc_samples_khz.append(round(fc_khz, 2))

            # Peaking calculation
            if zeta < (1.0 / math.sqrt(2.0)):
                mp_lin = 1.0 / (2.0 * zeta * math.sqrt(max(0.01, 1.0 - zeta * zeta)))
                mp_db = 20.0 * math.log10(max(1.0, mp_lin))
            else:
                mp_db = 0.0
            peaking_samples_db.append(round(mp_db, 2))

            # Spec check: fc in [70, 90] kHz and peaking < 1.5 dB
            is_pass = (self.SPEC_MIN_FC_KHZ <= fc_khz <= self.SPEC_MAX_FC_KHZ) and (mp_db <= self.SPEC_MAX_PEAKING_DB)
            in_spec_flags.append(is_pass)

        # Statistical Metrics
        num_pass = sum(1 for p in in_spec_flags if p)
        yield_pct = round((num_pass / float(n_trials)) * 100.0, 1)

        mean_fc = round(sum(fc_samples_khz) / float(n_trials), 2)
        variance_fc = sum((x - mean_fc) ** 2 for x in fc_samples_khz) / float(n_trials - 1)
        std_fc = round(math.sqrt(variance_fc), 2)
        min_fc = min(fc_samples_khz)
        max_fc = max(fc_samples_khz)

        # 20 Histogram Bins
        hist_min = math.floor(min(min_fc, self.SPEC_MIN_FC_KHZ - 5.0))
        hist_max = math.ceil(max(max_fc, self.SPEC_MAX_FC_KHZ + 5.0))
        bin_width = (hist_max - hist_min) / float(num_bins)

        bin_centers = [round(hist_min + (i + 0.5) * bin_width, 1) for i in range(num_bins)]
        in_spec_counts = [0] * num_bins
        out_of_spec_counts = [0] * num_bins

        for idx, fc in enumerate(fc_samples_khz):
            b_idx = int((fc - hist_min) / bin_width)
            b_idx = max(0, min(num_bins - 1, b_idx))
            if in_spec_flags[idx]:
                in_spec_counts[b_idx] += 1
            else:
                out_of_spec_counts[b_idx] += 1

        # Sensitivity / Tornado Variance Decomposition (Pearson correlation squared)
        def corr(xs, ys):
            mx = sum(xs) / len(xs)
            my = sum(ys) / len(ys)
            num = sum((x - mx) * (y - my) for x, y in zip(xs, ys))
            den = math.sqrt(sum((x - mx) ** 2 for x in xs) * sum((y - my) ** 2 for y in ys))
            return abs(num / max(1e-9, den))

        r_c1 = corr(c_samples, fc_samples_khz) ** 2
        r_r1 = corr(r_samples, fc_samples_khz) ** 2
        r_cpar = corr(cpar_samples, fc_samples_khz) ** 2
        total_r2 = r_c1 + r_r1 + r_cpar

        sensitivity_ranking = [
            {
                "component": "C1 (Feedback Capacitor)",
                "nominal": "2.0 pF",
                "tolerance_pct": round(c_tol * 100.0, 1),
                "variance_impact_pct": round((r_c1 / max(1e-6, total_r2)) * 100.0, 1),
                "recommendation": "Tighten to ±1% C0G/NP0 dielectric to maximize manufacturing yield"
            },
            {
                "component": "R1 (Feedback Resistor)",
                "nominal": "1.0 MOhm",
                "tolerance_pct": round(r_tol * 100.0, 1),
                "variance_impact_pct": round((r_r1 / max(1e-6, total_r2)) * 100.0, 1),
                "recommendation": "0.1% thin-film resistor ensures low drift"
            },
            {
                "component": "C_par (PCB Trace Parasitic)",
                "nominal": "1.2 pF",
                "tolerance_pct": round(par_tol * 100.0, 1),
                "variance_impact_pct": round((r_cpar / max(1e-6, total_r2)) * 100.0, 1),
                "recommendation": "Guard ring spacing and soldermask clearance stabilize capacitance"
            }
        ]

        return {
            "num_runs": n_trials,
            "yield_percent": yield_pct,
            "pass_count": num_pass,
            "fail_count": n_trials - num_pass,
            "mean_cutoff_khz": mean_fc,
            "std_cutoff_khz": std_fc,
            "min_cutoff_khz": min_fc,
            "max_cutoff_khz": max_fc,
            "spec_limits_khz": [self.SPEC_MIN_FC_KHZ, self.SPEC_MAX_FC_KHZ],
            "spec_max_peaking_db": self.SPEC_MAX_PEAKING_DB,
            "histogram": {
                "bin_centers_khz": bin_centers,
                "bin_width_khz": round(bin_width, 2),
                "in_spec_counts": in_spec_counts,
                "out_of_spec_counts": out_of_spec_counts
            },
            "sensitivity_ranking": sensitivity_ranking,
            "tolerances_used": {
                "r1_tolerance_pct": round(r_tol * 100.0, 1),
                "c1_tolerance_pct": round(c_tol * 100.0, 1),
                "parasitic_tolerance_pct": round(par_tol * 100.0, 1)
            }
        }
