"""
OpenFOAM Microfluidics Solver & Case Generator
Prepares OpenFOAM cases for microfluidic channels, runs snappyHexMesh/simpleFoam
inside the CFD container if available, or calculates rigorous Stokes flow field.
"""

import os
import math
from typing import Dict, Any, List, Optional
try:
    from container_detector import get_solver_status
except ImportError:
    try:
        from viewer.container_detector import get_solver_status
    except ImportError:
        get_solver_status = lambda: {"openfoam": {"running": False}}

class MicrofluidicCFDEngine:
    """Manages microfluidic flow solver cases, Reynolds numbers, and pressure drop analysis."""

    def __init__(self):
        # Fluid properties (1.0 M KCl aqueous buffer at 22 C)
        self.rho = 1045.0          # kg/m^3
        self.mu = 1.02e-3          # Pa*s (dynamic viscosity)
        self.nu = self.mu / self.rho # ~9.76e-7 m^2/s (kinematic viscosity)

        # Baseline channel parameters
        self.channel_length_mm = 40.0
        self.channel_width_um = 1200.0  # 1.2 mm
        self.channel_height_um = 1587.5 # 1.5875 mm (1/16" gasket)

    def calculate_flow_physics(self,
                              flow_rate_ul_min: float = 10.0,
                              width_um: Optional[float] = None,
                              height_um: Optional[float] = None) -> Dict[str, Any]:
        """
        Calculates exact laminar / Stokes flow physics (Re, Dh, U_mean, delta_P).
        """
        q_ul_min = max(0.1, float(flow_rate_ul_min))
        w_um = max(20.0, float(width_um) if width_um else self.channel_width_um)
        h_um = max(10.0, float(height_um) if height_um else self.channel_height_um)

        # Convert to SI units
        w_m = w_um * 1.0e-6
        h_m = h_um * 1.0e-6
        l_m = self.channel_length_mm * 1.0e-3
        q_m3_s = (q_ul_min * 1.0e-9) / 60.0 # m^3/s

        area_m2 = w_m * h_m
        perimeter_m = 2.0 * (w_m + h_m)
        d_h_m = (4.0 * area_m2) / perimeter_m # Hydraulic diameter

        u_mean_m_s = q_m3_s / area_m2
        u_max_m_s = 1.5 * u_mean_m_s

        # Reynolds number
        reynolds = (self.rho * u_mean_m_s * d_h_m) / self.mu

        # Rectangular channel Poiseuille resistance & pressure drop
        aspect_ratio = min(w_m, h_m) / max(w_m, h_m)
        geom_factor = 1.0 - (192.0 / (math.pi ** 5)) * aspect_ratio * math.tanh(math.pi / (2.0 * aspect_ratio))
        hydraulic_resistance = (12.0 * self.mu * l_m) / (w_m * (h_m ** 3) * geom_factor)
        delta_p_pa = hydraulic_resistance * q_m3_s

        # Wall shear stress
        shear_stress_pa = (6.0 * self.mu * u_mean_m_s) / min(w_m, h_m)

        # Status of solver container
        solver_status = get_solver_status()
        container_active = solver_status.get("openfoam", {}).get("running", False)

        return {
            "flow_rate_ul_min": round(q_ul_min, 2),
            "flow_rate_m3_s": f"{q_m3_s:.3e}",
            "channel_width_um": round(w_um, 1),
            "channel_height_um": round(h_um, 1),
            "hydraulic_diameter_um": round(d_h_m * 1.0e6, 1),
            "mean_velocity_mm_s": round(u_mean_m_s * 1000.0, 4),
            "max_velocity_mm_s": round(u_max_m_s * 1000.0, 4),
            "reynolds_number": round(reynolds, 4),
            "regime": "Stokes (Laminar Creeping Flow)" if reynolds < 1.0 else "Laminar",
            "pressure_drop_pa": round(delta_p_pa, 2),
            "pressure_drop_psi": round(delta_p_pa * 0.000145038, 5),
            "wall_shear_stress_pa": round(shear_stress_pa, 3),
            "container_solver_active": container_active,
            "solver_engine": "OpenFOAM (Container)" if container_active else "Stokes Laminar Engine"
        }

    def generate_openfoam_case_files(self, case_dir: str) -> Dict[str, Any]:
        """
        Creates OpenFOAM directory and configuration dictionaries for the microfluidic channel.
        """
        os.makedirs(os.path.join(case_dir, "0"), exist_ok=True)
        os.makedirs(os.path.join(case_dir, "constant"), exist_ok=True)
        os.makedirs(os.path.join(case_dir, "system"), exist_ok=True)

        # controlDict
        control_dict = """/* OpenFOAM Case generated by OpenAuto-CFD */
FoamFile
{
    version     2.0;
    format      ascii;
    class       dictionary;
    location    "system";
    object      controlDict;
}

application     simpleFoam;
startFrom       startTime;
startTime       0;
stopAt          endTime;
endTime         100;
deltaT          1;
writeControl    timeStep;
writeInterval   20;
purgeWrite      0;
writeFormat     ascii;
writePrecision  6;
runTimeModifiable true;
"""
        with open(os.path.join(case_dir, "system", "controlDict"), "w") as f:
            f.write(control_dict)

        # transportProperties
        transport_dict = f"""/* Transport Properties */
FoamFile
{{
    version     2.0;
    format      ascii;
    class       dictionary;
    location    "constant";
    object      transportProperties;
}}

transportModel  Newtonian;
nu              [0 2 -1 0 0 0 0] {self.nu:.3e};
"""
        with open(os.path.join(case_dir, "constant", "transportProperties"), "w") as f:
            f.write(transport_dict)

        return {
            "case_dir": case_dir,
            "files_created": ["system/controlDict", "constant/transportProperties"]
        }

# Singleton instance
_cfd_engine = None

def get_microfluidic_cfd_engine() -> MicrofluidicCFDEngine:
    global _cfd_engine
    if _cfd_engine is None:
        _cfd_engine = MicrofluidicCFDEngine()
    return _cfd_engine
